[build]
publish = "site/public"
command = "cd site && hugo --themesDir=../.. --baseURL $URL"

[build.environment]
HUGO_VERSION = "0.77.0"
HUGO_THEME = "repo"

[context.deploy-preview]
command = "cd site &&  hugo --themesDir=../.. --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL"
